language: node_js

node_js:
    - "0.10.20"

before_install:
    - rvm
        - 2.0.0 --fuzzy
    - python
        - 2.7.6 --fuzzy

install:
    - npm install -g grunt-cli
    - npm install
    - grunt install
    - rm -r *.lock

after_success:
    - grunt test
