name: slcli
summary: A CLI tool to interact with the SoftLayer API.
version: 'git'
adopt-info: slcli
description: |
    A command-line interface is also included and can be used to manage various SoftLayer products and services.

license: MIT

base: core18
grade: stable 
confinement: strict

apps:
  slcli:
    command: slcli
    environment: 
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      - network-bind
     
parts: 
  slcli:
    source: https://github.com/softlayer/softlayer-python
    source-type: git
    plugin: python
    python-version: python3
   
    build-packages:
      - python3
      
    stage-packages:
      - python3
